# Generated by Django 4.2.1 on 2023-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
